#%RAML 0.8
title: OICCalorificValue
version: v1.1.0-2018
documentation:
  - title: (c) 2018 Open Connectivity Foundation, Inc. All rights reserved.
    content: |
        Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
        1.  Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
        2.  Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

        THIS SOFTWARE IS PROVIDED BY THE Open Connectivity Foundation, INC. "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE OR WARRANTIES OF NON-INFRINGEMENT, ARE DISCLAIMED. IN NO EVENT SHALL THE Open Connectivity Foundation, INC. OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
schemas:
  - Calorific: !include oic.r.calorific.value.json

traits:
  - interface:
      queryParameters:
        if:
          enum: ["oic.if.s","oic.if.rw"]

/CalorificValueResURI:
  description: |
    This Resource describes Properties associated with the energy associated with the consumption of different fuels (including natural gas)
    The calorific value is a number

  displayName: Calorific Value of a fuel
  is: [ interface ] # valid for all methods

  get:
    description: |
      the calorific value is a measure of the available heat energy, used as part of the calculation to convert a
      volume of a fuel (e.g. m3) to an energy value (e.g. KWh).
    responses:
      200:
        body:
          application/json:
            schema: Calorific
            example: |
              {
                "rt":     ["oic.r.calorific.value"],
                "id":     "unique_example_id",
                "calorific":  39.2,
              }
